Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vm.provision :shell, :path => "provision.sh"
  config.vm.network :forwarded_port, guest:4444, host:4444
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    #v.gui = true
  end
  config.vm.synced_folder "./", "/vagrant"
end
